version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: postgres_db_service
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgvector-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_service
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped
  api:
    build: .
    container_name: agent_api_service
    env_file:
      - .env
    ports:
      - "8085:8085"
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    restart: unless-stopped
volumes:
  pgvector-data: