services:
  api:
    build: .
    container_name: agent_api_service
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    restart: unless-stopped
volumes:
  pgvector-data: